### ISSUE TITLE
onScrollListener doesn't respond with asynchronous call back

### ISSUE THREAD

**Issue by WenhaoWu** [lantouzi/WheelView-Android#6]
I try to use this library with asynchronous call back but after it draws the view it does not respond to scrolling event. However the onClick method for single item works perfectly. Any idea why?

Here is my demo code;
             
                
        mWheelView = (WheelView) findViewById(R.id.wheelview);

		RequestQueue queue = Volley.newRequestQueue(this);
		String url ="http://demo6559657.mockable.io/quest2";

		StringRequest stringRequest = new StringRequest(Request.Method.GET, url,
				new Response.Listener<String>() {
					@Override
					public void onResponse(String response) {
						final List<String> items = new ArrayList<>();
						for (int i = 1; i <= 40; i++) {
							items.add(String.valueOf(i * 1000));
						}

						mWheelView.setItems(items);

					}
				}, new Response.ErrorListener() {
			@Override
			public void onErrorResponse(VolleyError error) {
				Toast.makeText(getBaseContext(), error.getMessage(), Toast.LENGTH_SHORT).show();
			}
		});

		queue.add(stringRequest);

**Comment by kyleduo** [comment]
Sorry it is a bug, you can use 1.1.2 version to make it work right now.
